"""Endpoint labelling for metrics and logs.

This is twenty lines of code guarding against the single most common way a
Prometheus deployment falls over: **label cardinality**.

If the raw request path is used as a label value, then ``/api/tasks/1/``,
``/api/tasks/2/`` and ``/api/tasks/3/`` are three different time series. With a
few thousand tasks the process runs out of memory building series that nobody
will ever query. Prometheus does not stop you; it just gets slower until it does
not work any more.

The fix is to label by the *URL pattern* Django resolved, so every task detail
request collapses into ``/api/tasks/<pk>/``. Requests that never reached the
resolver (a 404, or something rejected by middleware) all collapse into a single
``unmatched`` series -- which is also exactly the signal you want when a scanner
is walking your site.
"""
from __future__ import annotations

import re

UNMATCHED = "unmatched"

# Longest label value we will emit. A resolver route is short by construction;
# this is a belt-and-braces guard so a pathological route cannot bloat every
# series and every log line that references it.
MAX_LABEL_LENGTH = 120

# DRF's router builds its routes as regular expressions, so a detail endpoint
# resolves to `^tasks/(?P<pk>[^/.]+)/$` rather than `tasks/<pk>/`. Both are
# bounded -- which is the property that matters -- but only one of them is
# readable on a Grafana legend, so the regex is rewritten into the `{name}`
# form Django uses for `path()` converters.
_PARAM_RE = re.compile(r"\(\?P<([^>]+)>[^)]*\)")


def normalise_endpoint(request) -> str:
    """Return a bounded-cardinality label for ``request``."""
    match = getattr(request, "resolver_match", None)
    route = getattr(match, "route", None) if match is not None else None

    if not route:
        # Either the request was rejected before routing (security middleware,
        # throttling) or it did not match any pattern. Both are "not a known
        # endpoint" and both are bounded.
        return UNMATCHED

    return _tidy_route(route)[:MAX_LABEL_LENGTH]


def _tidy_route(route: str) -> str:
    """Turn a Django route pattern into a stable, human-readable label.

    ``api/tasks/$``             -> ``/api/tasks/``
    ``api/tasks/(?P<pk>[^/.]+)/$`` -> ``/api/tasks/{pk}/``
    """
    cleaned = route.strip()
    if cleaned.startswith("^"):
        cleaned = cleaned[1:]
    if cleaned.endswith("$"):
        cleaned = cleaned[:-1]
    cleaned = _PARAM_RE.sub(r"{\1}", cleaned)
    if not cleaned.startswith("/"):
        cleaned = "/" + cleaned
    return cleaned


# Probe traffic is excluded from every SLI. These requests are generated by
# monitoring infrastructure on a fixed schedule, they are not user requests, and
# counting them would let the monitoring system flatter its own availability
# number -- a probe loop that never fails would drag the measured error rate
# towards zero no matter what real users experienced.
PROBE_ENDPOINTS = frozenset({"/healthz/", "/readyz/", "/metrics", "/version/"})


def is_probe_endpoint(endpoint: str) -> bool:
    return endpoint in PROBE_ENDPOINTS
